/**
 * magazine.ts — publication logic + dynamic internal-link graph for the dark-tourism magazine.
 *
 * SERVER-ONLY (uses fs at build time). Everything renders to static HTML during
 * `next build` (output: "export"), so Google sees full content — never a client shell.
 *
 * Source of truth:
 *   src/data/magazine-pages.json   briefs + publishAt (generated by scripts/excel-to-magazine.py)
 *   src/data/magazine-links.json   internal-link graph keyed by source URL
 *   content/magazine/<slug>.md     hand-written article (gray-matter frontmatter + markdown body)
 *
 * A page is LIVE only when its .md exists, is not draft, and (in prod) its publishAt is reached.
 */
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { SITE_URL } from "@/lib/seo";

const ROOT = process.cwd();
const PAGES_FILE = path.join(ROOT, "src/data/magazine-pages.json");
const LINKS_FILE = path.join(ROOT, "src/data/magazine-links.json");
const CONTENT_DIR = path.join(ROOT, "content/magazine");

export interface MagazinePage {
  id: string | number;
  slug: string;
  url: string;
  type: string;
  cluster: string | null;
  region: string | null;
  country: string | null;
  priority: string | null;
  clickDepth: number | null;
  parentUrl: string | null;
  title: string | null;
  h1: string | null;
  primaryKeyword: string | null;
  secondaryKeywords: string[];
  searchIntent: string | null;
  audienceDesire: string | null;
  serpAngle: string | null;
  planMetaTitle: string | null;
  planMetaDescription: string | null;
  h2Outline: string[];
  faqQuestions: string[];
  semanticEntities: string[];
  requiredInternalLinks: string[];
  sourceUrl: string | null;
  claudePrompt: string | null;
  guardrail: string | null;
  publishBatch: string | null;
  publishAt: string; // YYYY-MM-DD
  isHub: boolean;
}

export interface MagazineLink {
  target: string;
  anchor: string;
  type: string;
  priority: string;
}

export interface ArticleFrontmatter {
  draft?: boolean;
  metaTitle?: string;
  metaDescription?: string;
  h1?: string;
  heroImage?: string;
  heroAlt?: string;
  minWords?: number;
  faq?: { q: string; a: string }[];
  sources?: string[];
}

export interface Article {
  slug: string;
  frontmatter: ArticleFrontmatter;
  body: string;
}

interface PagesFile {
  meta: {
    schedule: { startDate: string; rampDays: number; rampPerDay: number; cruisePerDay: number; lastPublishAt: string };
    magazineRoot: string;
    counts: { total: number; byType: Record<string, number> };
  };
  pages: MagazinePage[];
}

/** Real public routes that already exist outside the magazine (trailingSlash: true). */
export const EXISTING_PUBLIC = new Set<string>([
  "/",
  "/about/",
  "/apply/",
  "/legal/",
  "/expeditions/",
]);

// ---- lazy singletons --------------------------------------------------------
let _data: PagesFile | null = null;
let _links: Record<string, MagazineLink[]> | null = null;
const _articleCache = new Map<string, Article | null>();

function data(): PagesFile {
  if (!_data) _data = JSON.parse(fs.readFileSync(PAGES_FILE, "utf8"));
  return _data!;
}
function linkGraph(): Record<string, MagazineLink[]> {
  if (!_links) _links = JSON.parse(fs.readFileSync(LINKS_FILE, "utf8"));
  return _links!;
}

export function magazineMeta() {
  return data().meta;
}
export function allPages(): MagazinePage[] {
  return data().pages;
}

const _byUrl = new Map<string, MagazinePage>();
const _bySlug = new Map<string, MagazinePage>();
function indexPages() {
  if (_byUrl.size) return;
  for (const p of allPages()) {
    _byUrl.set(normalizeUrl(p.url), p);
    _bySlug.set(p.slug, p);
  }
}
export function getPageByUrl(url: string): MagazinePage | undefined {
  indexPages();
  return _byUrl.get(normalizeUrl(url));
}
export function getPageBySlug(slug: string): MagazinePage | undefined {
  indexPages();
  return _bySlug.get(slug);
}

// ---- dates ------------------------------------------------------------------
/** Build date (YYYY-MM-DD). Override with SEO_BUILD_DATE to simulate a future day. */
export function buildDate(): string {
  const env = process.env.SEO_BUILD_DATE;
  if (env && /^\d{4}-\d{2}-\d{2}$/.test(env)) return env;
  return new Date().toISOString().slice(0, 10);
}
function publicationDate(): string {
  const start = data().meta.schedule.startDate;
  const b = buildDate();
  return b < start ? start : b;
}
/** In `next dev` everything written is visible; the date gate only applies to the prod build. */
function isDevServer(): boolean {
  return process.env.NODE_ENV !== "production";
}

// ---- content files ----------------------------------------------------------
export function getArticle(slug: string): Article | null {
  if (_articleCache.has(slug)) return _articleCache.get(slug)!;
  const file = path.join(CONTENT_DIR, `${slug}.md`);
  let article: Article | null = null;
  if (fs.existsSync(file)) {
    const parsed = matter(fs.readFileSync(file, "utf8"));
    article = { slug, frontmatter: parsed.data as ArticleFrontmatter, body: parsed.content.trim() };
  }
  _articleCache.set(slug, article);
  return article;
}
export function hasContent(slug: string): boolean {
  return getArticle(slug) !== null;
}

// ---- publication ------------------------------------------------------------
export function isPublished(page: MagazinePage | undefined): boolean {
  if (!page) return false;
  const article = getArticle(page.slug);
  if (!article) return false;
  if (article.frontmatter.draft === true) return false;
  if (isDevServer()) return true;
  return page.publishAt <= publicationDate();
}

export function getPublishedPages(): MagazinePage[] {
  return allPages().filter(isPublished);
}

// ---- URL helpers ------------------------------------------------------------
export function normalizeUrl(href: string): string {
  if (!href) return href;
  let u = href.split("#")[0].split("?")[0];
  if (!u.startsWith("/")) return href; // external
  if (!u.endsWith("/")) u += "/";
  return u;
}

let _publicSet: Set<string> | null = null;
function publicUrlSet(): Set<string> {
  if (_publicSet) return _publicSet;
  _publicSet = new Set(EXISTING_PUBLIC);
  for (const p of getPublishedPages()) _publicSet.add(normalizeUrl(p.url));
  return _publicSet;
}

/** Is an internal href live right now? Drives auto-activating body links (zero 404). */
export function isUrlPublished(href: string): boolean {
  const u = normalizeUrl(href);
  if (!u.startsWith("/")) return false;
  if (u.startsWith("/expeditions/")) return true; // individual expedition pages are real
  return publicUrlSet().has(u);
}

// ---- breadcrumb -------------------------------------------------------------
export interface Crumb {
  name: string;
  url: string;
}
export function buildBreadcrumb(page: MagazinePage): Crumb[] {
  const crumbs: Crumb[] = [{ name: "Home", url: "/" }];
  const chain: MagazinePage[] = [];
  let cur: MagazinePage | undefined = page;
  const guard = new Set<string>();
  while (cur && cur.parentUrl && !guard.has(cur.url)) {
    guard.add(cur.url);
    const parent = getPageByUrl(cur.parentUrl);
    if (!parent) break;
    if (isPublished(parent)) chain.unshift(parent);
    cur = parent;
  }
  for (const p of chain) crumbs.push({ name: crumbLabel(p), url: p.url });
  crumbs.push({ name: crumbLabel(page), url: page.url });
  return crumbs;
}
function crumbLabel(p: MagazinePage): string {
  return (p.h1 || p.title || p.url).replace(/\s*[—-]\s*Ligne Rouge.*$/i, "").trim();
}

// ---- internal-link blocks (dynamic maillage) --------------------------------
export interface LinkBlock {
  heading: string;
  links: { url: string; anchor: string }[];
}

function resolveAnchor(target: string, fallbackAnchor: string): string {
  if (fallbackAnchor && fallbackAnchor.trim()) return fallbackAnchor.trim();
  const p = getPageByUrl(target);
  return (p?.h1 || p?.title || target) as string;
}

/**
 * Returns the "see also" blocks for a page, built from the link graph, filtered to
 * pages that are LIVE right now and deduped. Parent links are omitted (breadcrumb covers them).
 */
export function getMaillage(page: MagazinePage): LinkBlock[] {
  const out: MagazineLink[] = (linkGraph()[page.url] || []).filter(
    (l) => l.type !== "Parent" && isUrlPublished(l.target) && normalizeUrl(l.target) !== normalizeUrl(page.url),
  );

  const seen = new Set<string>();
  const siblings: { url: string; anchor: string }[] = [];
  const safety: { url: string; anchor: string }[] = [];

  for (const l of out) {
    const u = normalizeUrl(l.target);
    if (seen.has(u)) continue;
    seen.add(u);
    const entry = { url: l.target, anchor: resolveAnchor(l.target, l.anchor) };
    if (l.type.toLowerCase().includes("safety") || l.type.toLowerCase().includes("ethic")) safety.push(entry);
    else if (l.type.toLowerCase().includes("global")) continue; // main hub already in breadcrumb/nav
    else siblings.push(entry);
  }

  // Children are rendered separately as cards (see getHubChildren), so they are
  // intentionally not duplicated here.
  const blocks: LinkBlock[] = [];
  if (siblings.length) blocks.push({ heading: "Related guides", links: siblings.slice(0, 8) });
  if (safety.length) blocks.push({ heading: "Before you go", links: safety });
  return blocks;
}

export function getHubChildren(page: MagazinePage): MagazinePage[] {
  return getPublishedPages()
    .filter((c) => c.parentUrl && normalizeUrl(c.parentUrl) === normalizeUrl(page.url))
    .sort((a, b) => (a.priority || "").localeCompare(b.priority || ""));
}

/** Published cluster hubs — used for primary navigation / the main hub index. */
export function getClusterHubs(): MagazinePage[] {
  return getPublishedPages()
    .filter((p) => p.type === "Cluster Hub")
    .sort((a, b) => (a.cluster || "").localeCompare(b.cluster || ""));
}

// ---- metadata helpers -------------------------------------------------------
export function effectiveMeta(page: MagazinePage, article: Article | null) {
  const fm = article?.frontmatter ?? {};
  return {
    metaTitle: fm.metaTitle || page.planMetaTitle || page.title || "",
    metaDescription: fm.metaDescription || page.planMetaDescription || "",
    h1: fm.h1 || page.h1 || page.title || "",
    canonical: `${SITE_URL}${normalizeUrl(page.url)}`,
  };
}
