project_id = "hyeqshzcujnupxxeocfy"

[functions.notify-application]
verify_jwt = false

[functions.notify-waitlist]
verify_jwt = false

[functions.notify-newsletter]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.prerender]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
