-- The previous testimonial batch tagged North Korea reviews "Expedition 2024" /
-- "Expedition 2025", implying the tour has been running normally right up to
-- now. That contradicts the tour's own cancellation notice: North Korea has
-- been closed to most international tourism for years, with only a brief,
-- narrow reopening before entry was suspended again. Dropped the year tags
-- (kept role/nationality only, matching the format already used elsewhere
-- for entries without a year) so the reviews don't imply recent, ongoing
-- departures. Same names/quotes/photos, just no false recency claim.
UPDATE public.expeditions SET testimonials = '[{"name": "Marco Antonio A.", "quote": "The mass games in the evening are unlike anything else on Earth, a scale of choreography that has to be seen to be believed.", "detail": "Mexico", "image_url": "https://randomuser.me/api/portraits/men/45.jpg"}, {"name": "Shrishti P.", "quote": "Visiting a rural cooperative farm outside Pyongyang gave a totally different picture than the capital alone would have.", "detail": "India", "image_url": "https://randomuser.me/api/portraits/women/44.jpg"}, {"name": "Raphaël B.", "quote": "The Kaesong visit and the Joint Security Area at the DMZ were tightly managed but genuinely fascinating to stand inside.", "detail": "Political science student - Switzerland", "image_url": "https://randomuser.me/api/portraits/men/46.jpg"}, {"name": "Ricarda J.", "quote": "Talking with people at the schools and factories we visited, guided as it obviously was, still gave real insight.", "detail": "Germany", "image_url": "https://randomuser.me/api/portraits/women/45.jpg"}, {"name": "Snaga B.", "quote": "The train journey in via Beijing sets the tone perfectly, that slow build of anticipation before Pyongyang comes into view.", "detail": "Ukraine", "image_url": "https://randomuser.me/api/portraits/men/47.jpg"}, {"name": "Zoraia C.", "quote": "This is closely guided access, not free-roaming travel, and understanding that going in made the whole week make more sense.", "detail": "Journalist - Brazil", "image_url": "https://randomuser.me/api/portraits/women/46.jpg"}, {"name": "Mason H.", "quote": "Seven days of total immersion into a country almost nobody gets to see from the inside. Genuinely unlike any other trip I''ve taken.", "detail": "Australia", "image_url": "https://randomuser.me/api/portraits/men/48.jpg"}]'::jsonb
  WHERE slug = 'north-korea-total-system-immersion';
